TICKER_KEYWORDS = {
    "AAPL": [
        "Apple Inc.",
        "iPhone",
        "Tim Cook",
        "MacBook",
        "iOS",
        "AirPods",
        "Apple Music",
        "Apple Pay",
        "Apple TV+",
        "iCloud",
    ],
    "MSFT": [
        "Microsoft",
        "Windows",
        "Satya Nadella",
        "Azure",
        "Xbox",
        "Surface",
        "Teams",
        "Power BI",
        "LinkedIn",
        "Office 365",
    ],
    "AMZN": [
        "Amazon",
        "AWS",
        "Jeff Bezos",
        "Prime",
        "Kindle",
        "Whole Foods",
        "Alexa",
        "Amazon Fresh",
        "Ring",
        "Fire TV",
    ],
    "GOOGL": [
        "Google",
        "Sundar Pichai",
        "Android",
        "YouTube",
        "Search",
        "Google Cloud",
        "AdSense",
        "Google Maps",
        "Pixel",
        "Waymo",
    ],
    "META": [
        "Facebook",
        "Mark Zuckerberg",
        "Instagram",
        "WhatsApp",
        "Oculus",
        "Meta Platforms",
        "Messenger",
        "Libra",
        "Portal",
        "Workplace",
    ],
    "TCEHY": [
        "Tencent",
        "Pony Ma",
        "WeChat",
        "QQ",
        "Tencent Music",
        "Tencent Cloud",
        "Honor of Kings",
        "Tencent Games",
        "Mini Programs",
        "WeBank",
    ],
    "BABA": [
        "Alibaba",
        "Jack Ma",
        "Taobao",
        "Tmall",
        "AliExpress",
        "Alipay",
        "Ant Group",
        "Cainiao",
        "Youku",
        "DingTalk",
    ],
    "NVDA": [
        "NVIDIA",
        "Jensen Huang",
        "GeForce",
        "CUDA",
        "Deep Learning",
        "AI",
        "RTX",
        "Tensor Core",
        "DLSS",
        "Arm Holdings",
    ],
    "TSLA": [
        "Tesla",
        "Elon Musk",
        "EV",
        "Model 3",
        "Gigafactory",
        "SolarCity",
        "Cybertruck",
        "Autopilot",
        "Powerwall",
        "Roadster",
    ],
    "PYPL": [
        "PayPal",
        "Dan Schulman",
        "Venmo",
        "Braintree",
        "PayPal Credit",
        "Xoom",
        "Honey",
        "Paydiant",
        "Hyperwallet",
        "iZettle",
    ],
    "ADBE": [
        "Adobe",
        "Shantanu Narayen",
        "Photoshop",
        "Creative Cloud",
        "PDF",
        "Lightroom",
        "Illustrator",
        "Premiere Pro",
        "Adobe Sign",
        "Magento",
    ],
    "INTC": [
        "Intel",
        "Pat Gelsinger",
        "x86",
        "Core i9",
        "Optane",
        "Thunderbolt",
        "Mobileye",
        "FPGA",
        "NAND",
        "Loihi",
    ],
    "CSCO": [
        "Cisco",
        "Chuck Robbins",
        "Webex",
        "Networking",
        "Switches",
        "Routers",
        "Firewall",
        "Meraki",
        "AppDynamics",
        "Duo Security",
    ],
    "ORCL": [
        "Oracle",
        "Larry Ellison",
        "Java",
        "Database",
        "ERP",
        "Cloud",
        "Exadata",
        "NetSuite",
        "PeopleSoft",
        "MySQL",
    ],
    "CRM": [
        "Salesforce",
        "Marc Benioff",
        "CRM",
        "Cloud",
        "Tableau",
        "Einstein",
        "Slack",
        "MuleSoft",
        "Trailhead",
        "Marketing Cloud",
    ],
    "SSNLF": [
        "Samsung",
        "Lee Jae-yong",
        "Galaxy",
        "Smart TV",
        "Exynos",
        "QLED",
        "Tizen",
        "Bixby",
        "Samsung Biologics",
        "Harman",
    ],
    "IBM": [
        "IBM",
        "Arvind Krishna",
        "Watson",
        "Mainframe",
        "Red Hat",
        "Quantum Computing",
        "Blockchain",
        "Cloud Pak",
        "Cognos",
        "z/OS",
    ],
    "SAP": [
        "SAP",
        "Christian Klein",
        "ERP",
        "HANA",
        "BusinessObjects",
        "S/4HANA",
        "SuccessFactors",
        "Concur",
        "Ariba",
        "Qualtrics",
    ],
    "ASML": [
        "ASML",
        "Peter Wennink",
        "EUV",
        "Lithography",
        "Photomask",
        "Holistic Lithography",
        "TWINSCAN",
        "Metrology",
        "Deep UV",
        "E-beam",
    ],
    "AMD": [
        "AMD",
        "Lisa Su",
        "Ryzen",
        "Radeon",
        "EPYC",
        "Threadripper",
        "RDNA",
        "Infinity Fabric",
        "Zen Architecture",
        "FidelityFX",
    ],
    "^GSPC": [
        "S&P 500",
        "Index Fund",
        "Equities",
        "Bull Market",
        "Bear Market",
        "Dividends",
        "Earnings",
        "Volatility",
        "Large Cap",
        "Small Cap",
    ],
    "SPY": [
        "SPDR",
        "ETF",
        "S&P 500",
        "Passive Investing",
        "Indexing",
        "Dividend Yield",
        "Expense Ratio",
        "Asset Allocation",
        "Liquidity",
        "Rebalancing",
    ],
}
